# Permalinks
permalink:      /:year-:month-:day/:title
future: true
timezone: Asia/Tokyo

# Setup
title:          ikenox.info
paginate:       5
baseurl:
url:            "https://ikenox.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name_ja: 池野直人
  name_en: Naoto Ikeno
  job: Software Engineer
  nickname: ikenox

# Accounts
accounts:
  github: ikenox
  twitter: ikenoxx
  facebook: na.ik.54

# Google analytics
google_analytics: UA-108087720-1

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/ikenox.github.io

# Gems
gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
