# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          ikenox.info
paginate:       5
baseurl:
url:            "https://ikenox.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:
  nickname:     ikenox
  url:
  email:

google_analytics: UA-108087720-1

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/ikenox.github.io

# Gems
gems:
  - jekyll-paginate
